

services:
  mysql:
    image: mysql:8.0
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: site-mysql
    restart: always
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
      - ./site.sql:/docker-entrypoint-initdb.d/site.sql

  backend:
    build: .
    container_name: site-back
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mysql

volumes:
  mysql_data:
